services:
  postgres:
    image: postgres:17-bookworm
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "54320:54320"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:8-bookworm
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network


  bot:
    build: .
    image: bot
    container_name: bot
    restart: always
    command: ["sh", "./entrypoint.sh"]
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
      - redis
    networks:
      - app-network


volumes:
  postgres-data:
  redis-data:

networks:
  app-network:
    driver: bridge
